name: Demo Continuos Integration and Continuous deployment

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dot net
      run: dotnet build --configuration Release
      working-directory: ./E-BookLibrary
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./E-BookLibrary
